### PR TITLE
immediately close the child handle for a pipe after retrieving all co…

### PR DESCRIPTION
**Pull request by schmunk42**
…ntent

prevents issues which can arise from getting content of blocking/non-blocking streams while running in FPM.

### CODE REVIEW

**Comment by mikehaertl** [comment]
I'm very averse to changing this. Whenever we touch this we see new reports about things breaking or blocked executions, see #20. I've already reverted a couple of fixes as each of them introduced new problems. 

So I don't want to change this before we can't clearly identify the issue in #20 and have test cases for it.

**Comment by mikehaertl** [comment]
@schmunk42 Have you also tried the proposed fix in #20? 

```
    // set streams to non blocking mode
    stream_set_blocking($pipes[1], 0);
    stream_set_blocking($pipes[2], 0)
```

Would this also fix your problem?

**Comment by schmunk42** [comment]
I remember now :)

I played around with `stream_set_blocking()`, but it appears that it already has the correct setting (blocking in my case).
Although I also found issues saying that the returned meta-data is not correct in all cases.

I think it would be nice to have a parameter for `stream_set_blocking()`, so it might be easier to debug this.

A parameter for switching the order of getting STDOUT and STDERR might be a bit overkill, but could also help - I am not sure here.

The idea behind my proposed change was just to close the stream, when finished reading, instead of having an open file handle for the first stream, when reading the second one.

We were seeing this problem in our logs: https://serverfault.com/questions/839135/nginx-php-fpm-child-exited-with-code-0
Log messages piled up to 50.000 per minute.

**Comment by schmunk42** [comment]
Maybe this could also be related to STDIN? Please see https://bugs.php.net/bug.php?id=73342

So shellcommand's `proc_open()` does not handle STDIN at all - it would be interesting to see if the bug can be avoided by using (and closing) also a descriptor, like:

     0   => array('pipe','r'),

**Comment by mikehaertl** [comment]
@schmunk42 Not sure if you're still using this library but maybe you could help testing PR https://github.com/mikehaertl/php-shellcommand/pull/41? I've now completely refactored the execution with `proc_open()` and try to use non-blocking mode whenever possible. This requires some nifty altnernating handling of the I/O streams, though. In my tests it worked fine, but I'd like to ensure that the new solution works reliably in all cases.

**Comment by schmunk42** [comment]
I'll try to take a look. My usage was mainly with this lib: https://github.com/omauger/docker-compose-php

Basically I wanted to immediately see the output from `docker-compose`.

**Comment by mikehaertl** [comment]
> Basically I wanted to immediately see the output from docker-compose.

Right, I remember now. Honestly I think that we can't support immediate output. If you check the code, using non-blocking streams is already complex enough. I can't think of an easy way how you'd implement that real-time output feature. So for that use case you'd need another library - or brew your own solution for that specific use case. I doubt that there's a simple generic solution.

**Comment by mikehaertl** [comment]
@schmunk42 Closing this for now as the original issue should be solved with 1.5.0. 

Regarding immediate output: 

I was thinking about a complete rewrite of the library with a cleaner interface. In theory I think immediate output would be possible - but at the cost that the code you need to write always becomes ugly. Basically you'd need a loop in your code, something like this:

```php
$command = new Command('sleep 20');
$command->runAsync();
while ($command->isRunning()) {
    echo $command->getOutput();
}
```

But to be on the safe side, that's not enough. You'd have to copy the logic to alternately check the stdin/stdout streams in your code: 

https://github.com/mikehaertl/php-shellcommand/blob/e7bdc8af74e7fcfcb5b6f7f58b3ae047ae47754b/src/Command.php#L408-L470

You always need to check how much of the input/output you've already sent/received.

The library could buffer this internally to make things a little easier (e.g. with [php://temp or php://memory](https://www.php.net/manual/en/wrappers.php.php)). But to be honest I feel like there's too many scenarios where things can go horribly wrong. Maintaning could soon become a nightmare.

So I'd say: If you need this, it's really better to build or own logic with `proc_open()` based on the loop I linked above and taylor it to fit your needs.

**Pull request closed without merging**
