### PR TITLE
Echoing forked process output to stdout on demand

### PR DESCRIPTION
**Pull request by Antoniossss**
Resolves https://github.com/mikehaertl/php-shellcommand/issues/11

### CODE REVIEW

**Comment by mikehaertl** [comment]
@Antoniossss See https://github.com/schmunk42/php-shellcommand/commit/1606eeffedfdc1a77ae19cf56f9c0c1edc780648#commitcomment-16438471. We don't want this class to echo out anything.

**Comment by Antoniossss** [comment]
@mikehaertl That is why it is on demand + output is bufferen anyway. In my case.
This may be not the exact feature that has been requested, but in my case, i needed such feature - forked process is a really long running one, and live output is must be to see if everything is running smoothly.

**Comment by schmunk42** [comment]
@Antoniossss 

Here's a snippet from my code....

```
    public function status($name)
    {
        $command = $this->createCommand();
        $command->addArg('status');
        $command->addArg($name);

        $this->execute($command->getExecCommand());
    }

    private function execute($command)
    {
        // "real time" output
        echo $command."\n";

        $handle = popen($command, 'r');
        while (!feof($handle)) {
            echo fgets($handle);
        }
        pclose($handle);
    }
```

**Comment by mikehaertl** [comment]
@Antoniossss Let's continue discussion in #11.

**Pull request closed without merging**
